ALTER TABLE stage_api_configs
  ADD COLUMN IF NOT EXISTS id integer NOT NULL DEFAULT nextval('stage_api_configs_id_seq'::regclass),
  ADD COLUMN IF NOT EXISTS stage_id integer NOT NULL,
  ADD COLUMN IF NOT EXISTS integration_id integer,
  ADD COLUMN IF NOT EXISTS endpoint_url text,
  ADD COLUMN IF NOT EXISTS http_method text NOT NULL DEFAULT 'POST'::text,
  ADD COLUMN IF NOT EXISTS headers jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS auth_type text DEFAULT 'none'::text,
  ADD COLUMN IF NOT EXISTS auth_secret_key text,
  ADD COLUMN IF NOT EXISTS request_mapping jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS request_template text,
  ADD COLUMN IF NOT EXISTS response_mapping jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS rules jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS timeout_seconds integer DEFAULT 30,
  ADD COLUMN IF NOT EXISTS max_retries integer DEFAULT 3,
  ADD COLUMN IF NOT EXISTS retry_delay_seconds integer DEFAULT 5,
  ADD COLUMN IF NOT EXISTS fallback_on_error text DEFAULT 'pending_review'::text,
  ADD COLUMN IF NOT EXISTS fallback_on_timeout text DEFAULT 'pending_review'::text,
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS test_mode boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS mock_response jsonb,
  ADD COLUMN IF NOT EXISTS created_by character varying,
  ADD COLUMN IF NOT EXISTS created_at timestamp without time zone NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone NOT NULL DEFAULT now();